{% set name = "lumen" %}
{% set version = "1.0.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfcd83ecf4b78887b027598a86ddd864e81df8da703f0ad2e8b8fabed15c82a3

build:
  noarch: python
  number: 0
  entry_points:
    - lumen = lumen.command:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - bokeh
    - numpy
    - sqlglot
    - chardet
    - python >={{ python_min }}
    - panel >=1.8.6
    - hvplot
    - holoviews >=1.17.0
    - pandas
    - packaging
    - intake <2
    - jinja2 >3.0
    - pyyaml
    - param >=2.2.1
    - duckdb >=1.2.0
    - griffe
    - instructor >=1.6.4
    - markitdown
    - nbformat
    - panel-graphic-walker >=0.6.4
    - panel-material-ui >=0.8.1
    - panel-splitjs
    - pyarrow
    - pydantic >=2.8.0
    - pydantic-extra-types
    - semchunk
    - sqlglotrs
    - tabulate
    - tiktoken

test:
  imports:
    - lumen
  requires:
    - pip
    - python {{ python_min }}
  commands:
    #- pip check
    - lumen --help

about:
  home: https://github.com/holoviz/lumen
  summary: Illuminate your data.
  description: |
    Lumen is a fully open-source and extensible agent based framework
    for chatting with data, text-to-SQL and for retrieval augmented
    generation (RAG). It implements a declarative specfication for
    expressing data pipelines, visualizations and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://lumen.holoviz.org/
  dev_url: https://github.com/holoviz/lumen

extra:
  recipe-maintainers:
    - ahuang11
    - hoxbro
    - philippjfr
